### ISSUE TITLE
Support Sequelize enums

### ISSUE THREAD

**Issue by lekoder** [cockroachdb/sequelize-cockroachdb#13]
I have a relatively new Sequelize-based application and wanted to try cockroachdb. Unfortunately, I have hit errors as soon as I connected to cockroach:
```
     SequelizeDatabaseError: syntax error at or near "type"
DROP TYPE IF EXISTS "public"."enum_status";
     ^
SequelizeDatabaseError: duplicate constraint name: "unique_key"
```
These are from a test suite that is passing against MySQL 5.6, Postgres 9.6 and Sqlite.

I'm using:
```
    "sequelize": "^4.2.1",
    "sequelize-cockroachdb": "^1.0.2"
```

**Comment by jordanlewis** [comment]
CockroachDB doesn't support user-defined types, so it also doesn't support things like `DROP TYPE`.

We have several tests for Sequelize against CockroachDB, but apparently we're missing a test case for whatever kind of initialization process you're using here. Would you mind sharing how your application is initialized?

Thanks!

**Comment by benesch** [comment]
I'm willing to bet there's an enum type in the model.

**Comment by lekoder** [comment]
@benesch is correct, there is enum type:
```
status: { type: ENUM("OK","ERROR"), allowNull: false }
```

**Comment by lekoder** [comment]
@jordanlewis what is the ultimate conclusion? Is this something that will be mapped in `sequelize-cocroachdb` to a compatible type, or is it a `wontfix`?

**Comment by jordanlewis** [comment]
We're not going to have user-defined types in CockroachDB in the near future.

We might be able to work around this by teaching the adapter to store enum types as strings in CockroachDB. I'm not sure how easy that will be.

**Comment by jordanlewis** [comment]
@justinj could you take a quick look at this?

**Comment by lekoder** [comment]
Storing enums as strings would work for me. That's actually a workaround I'm using right now.
