### ISSUE TITLE
Schema "crdb_internal" does not exist

### ISSUE THREAD

**Issue by atjhoendz** [cockroachdb/sequelize-cockroachdb#138]
Previously I used [sequelize](https://github.com/sequelize/sequelize) with dialect postgres, and I try to move to cockroachdb using this library with the same model, overall CRUD process is working but the logger says:

```
Could not record telemetry.
SequelizeDatabaseError: schema "crdb_internal" does not exist.
```

this is my crdb_internal schema that already exists.

<img width="820" alt="Screen Shot 2021-12-15 at 15 13 01" src="https://user-images.githubusercontent.com/21331971/146148949-3eaaee46-571f-439f-aecd-014b0614d0b8.png">

I already force sync but the error log still exists

any thoughts on this?

**Comment by rafiss** [comment]
The error message referring to the call to this builtin function (used to let CRDB know that the tool being used is sequelize). https://github.com/cockroachdb/sequelize-cockroachdb/blob/a0ae8eab1c51baef1dc968a223685c4daa02a422/source/telemetry.js#L22

The error is not expected though. Which version of CockroachDB are you using?

**Comment by atjhoendz** [comment]
I using `v21.2.2` with docker

**Comment by atjhoendz** [comment]
btw there is no `increment_feature_counter` table in my `crdb_internal` schema

**Comment by atjhoendz** [comment]
I think I know the problem, this line should have an  `await` statement because this condition is a promise. I'll make PR for the solution

https://github.com/cockroachdb/sequelize-cockroachdb/blob/a0ae8eab1c51baef1dc968a223685c4daa02a422/source/telemetry.js#L16

**Comment by atjhoendz** [comment]
please kindly review sir https://github.com/cockroachdb/sequelize-cockroachdb/pull/139 @rafiss

TIA.

**Comment by rafiss** [comment]
Thanks for your fix. I've merged it and will publish a new release soon. However, I'm still not sure why you would have this error on CockroachDB v21.2.2. Are you sure you are not using an older version of CockroachDB?

**Comment by atjhoendz** [comment]
I don't know sir. Yes, I'm pretty sure, this is part of my docker-compose config. After I fixed that promise condition, the error log has been disappeared now.

![Screen Shot 2021-12-17 at 13 08 55](https://user-images.githubusercontent.com/21331971/146497586-107811a2-c643-4963-b82f-330296e779d4.png)

**Comment by rafiss** [comment]
Hm, ok glad it's working better now! Perhaps there is some race condition. Thanks again for noticing this and fixing it.

**Comment by atjhoendz** [comment]
My pleasure 👌
