### ISSUE TITLE
Why this package is needed?

### ISSUE THREAD

**Issue by williamoliveira** [cockroachdb/sequelize-cockroachdb#151]
Why does this exists exactly? isn't cockroachdb supposed to postgres compatible?

**Comment by dikshant** [comment]
👋🏽 Hi, while CockroachDB is wire compatible with Postgres and does support a majority of Postgres features, there are always edge cases where we may not be identical. You can read about some of the differences [here](https://www.cockroachlabs.com/docs/stable/postgresql-compatibility.html).
We do a significant amount of work to ensure CockroachDB remains compatible with a wide variety of developer toolings and this repo is part of that initiative to properly support Sequelize.
