### ISSUE TITLE
Model.findOrCreate rejects with error

### ISSUE THREAD

**Issue by lekoder** [cockroachdb/sequelize-cockroachdb#16]
When trying to use `Model.findOrCreate`, sequelize rejects operation with:

```
SequelizeDatabaseError: syntax error at or near "or"
CREATE OR REPLACE FUNCTION pg_temp.testfunc( [...]
       ^
```
sequelize: **4.8.4**
sequelize-cockroachdb **1.0.2**

**Comment by benesch** [comment]
Sorry about this! This looks to be a duplicate of #15, though, so closing to centralize discussion there.
