### ISSUE TITLE
Expect for a new releae.

### ISSUE THREAD

**Issue by vibolvireak** [cockroachdb/sequelize-cockroachdb#23]
Hello,

Is project still in development?  Any plan to release more commit? 
I saw the latest release is v1.0.2 on Aug 9, 2017. More than haft of year still no further update.
I just start develop some app using this driver and it is really useful for nodejs developer like me.

Thank you

**Comment by jordanlewis** [comment]
Hi @vibolvireak,

Yes, we plan to update this as necessary. However, we don't have many resources to devote to it. If you find issues, please let us know and we can try to fix them as necessary.
