### ISSUE TITLE
not really an issue, but an observation

### ISSUE THREAD

**Issue by edwardsmarkf** [cockroachdb/sequelize-cockroachdb#3]
hello -- 

i switched over from mariadb(mysql) over to cockroachdb with a mere ONE-LINE change in the node-script code, and this new interface performed perfectly and flawlessly.

i am **_VERY IMPRESSED_**.

**Comment by benesch** [comment]
Glad to hear it, @edwardsmarkf! We love hearing success stories.

Going to close this just so it doesn't look like there's an outstanding bug—but do let us know if you run into any problems.
