### ISSUE TITLE
Remove workaround for ENUMs for CockroachDB v20.2 and later

### ISSUE THREAD

**Issue by rafiss** [cockroachdb/sequelize-cockroachdb#44]
PR https://github.com/cockroachdb/sequelize-cockroachdb/pull/17 added a workaround to make enums backed by text columns. With the 20.2 releae, that is no longer necessary.

**Comment by douglasselias** [comment]
[Done](https://github.com/cockroachdb/sequelize-cockroachdb/pull/58)
