### ISSUE TITLE
describeTable query in Sequelize 5.21.3 using syntax that is invalid for CRDB

### ISSUE THREAD

**Issue by jhatcher9999** [cockroachdb/sequelize-cockroachdb#45]
Testing with Sequelize 5.21.3.

A call to: query.describeTable('xyz') creates this query:
```
SELECT
  pk.constraint_type as "Constraint",c.column_name as "Field",
  c.column_default as "Default",
  c.is_nullable as "Null",
  (
    CASE
      WHEN c.udt_name = 'hstore' THEN c.udt_name
      ELSE c.data_type
    END
  )
  ||
  (
    CASE
      WHEN c.character_maximum_length IS NOT NULL THEN '('
      ||
      c.character_maximum_length || ')' ELSE ''
    END
  ) as "Type",
  (
    SELECT array_agg(e.enumlabel)
    FROM pg_catalog.pg_type t
    JOIN pg_catalog.pg_enum e ON t.oid=e.enumtypid
    WHERE t.typname=c.udt_name
  ) AS "special",
  (
    SELECT pgd.description
    FROM pg_catalog.pg_statio_all_tables AS st
    INNER JOIN pg_catalog.pg_description pgd on (pgd.objoid = st.relid)
    WHERE c.ordinal_position = pgd.objsubid AND c.table_name = st.relname
  ) AS "Comment"
FROM information_schema.columns c
LEFT JOIN
(
  SELECT tc.table_schema, tc.table_name, cu.column_name, tc.constraint_type
  FROM information_schema.TABLE_CONSTRAINTS tc
  JOIN information_schema.KEY_COLUMN_USAGE  cu ON tc.table_schema=cu.table_schema and tc.table_name=cu.table_name and tc.constraint_name=cu.constraint_name and tc.constraint_type='PRIMARY KEY'
) pk ON pk.table_schema=c.table_schema
AND pk.table_name=c.table_name
AND pk.column_name=c.column_name
WHERE c.table_name = 'xyz' AND c.table_schema = 'public';
```

This query has two pieces that are not supported in CRDB (v20.1):
1) ERROR: incompatible value type: unsupported binary operator: <string> || <int>

This can be fixed by adding a `CAST( ... as VARCHAR)` on c.character_maximum_length

2) ERROR: unimplemented: virtual schema table not implemented: pg_catalog.pg_statio_all_tables
SQLSTATE: 0A000
HINT: You have attempted to use a feature that is not yet implemented.

Please check the public issue tracker to check whether this problem is
already tracked. If you cannot find it there, please report the error
with details by creating a new issue.

If you would rather not post publicly, please contact us directly
using the support form.

I'm not sure how to fix this since I'm not sure if there is another structure that supplies the table's comment.

**Comment by rafiss** [comment]
We should investigate if our adapter can override `describeTable` and modify the query so it works. Both are easy workarounds, if so: instead of `pg_statio_all_tables` use `pg_class` instead; and add casts to the query.

**Comment by rafiss** [comment]
This should be fixed now.
