### ISSUE TITLE
Fetch methods findAll/findOne returns integer type values as string.

### ISSUE THREAD

**Issue by Majid-Sohail** [cockroachdb/sequelize-cockroachdb#50]
When I fetch records the integer values always comes as string. For example
{
      "value": "8",
      "dateTime": "2020-11-30T08:42:17.000Z"
}.
In above example the value should b 8 not "8".

**Comment by rafiss** [comment]
cc @papb would you be able to make sure this gets addressed as part of your work? I am guessing that one of the new tests that you are enabling will cover this, but just want to make sure.

**Comment by papb** [comment]
Hello, indeed several of the tests I'm enabling with the last PR are failing with this exact issue. Hopefully it's not hard to fix.

**Comment by Sy1v4in** [comment]
Hello,

I tried with the release `6.0.0-alpha.0` but I still have this issue 😢 .

**Comment by rafiss** [comment]
@Sy1v4in Thanks for trying out the alpha version! This functionality still has issues in the alpha, but we're actively working on it now. We should have a full release soon.

**Comment by RichardJCai** [comment]
Fixed by https://github.com/cockroachdb/sequelize-cockroachdb/pull/80/
